name: future_foundation
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    get_it: ^4.0.4
    logger: ^0.9.2
    stacked: ^1.7.6
    stacked_services: ^0.5.4+2
    responsive_builder: ^0.2.0+2
    equatable: ^1.2.4
    flutter_icons: ^1.0.0+1
    font_awesome: ^5.10.1
    animated_splash_screen: ^1.0.1+2
    mask_text_input_formatter: ^1.2.1
    page_transition: ^1.1.7+6
    flutter_screenutil: ^4.0.3+2
    google_fonts: ^1.1.1
    url_launcher: ^6.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/
